spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/ps}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver